### ISSUE TITLE
Save button disappears

### ISSUE THREAD

**Issue by havarha** [cosmocode/edittable#86] opened 2015-08-27 18:04 UTC
I use edittable and the starter bootstrap template (https://www.dokuwiki.org/template:starterbootstrap). Everything has been working fine until the other day, when I was editing a table of 48 rows. When adding a new row, editing a value in an existing cell etc the save button would disappear, and some of the other buttons would also move up on the page or disappear.

I guess this could also be a template plugin, but this has worked perfectly for a long time, and I haven't updated the template. I did update the plugin today, but that didn't help.

Any clue why this could be happening?

**Comment by winnuker** [comment] 2015-09-01 07:39
Same here with large tables.

Firefox (40.0.2) and Chorme (45) with DokuWiki Template:
Edit big table
24 Rows are shown.
Click on the table -> 37 rows are shown.
Click on the table -> 52 rows are shown.
Click on the table -> 70 rows are shown.
Click on the table -> all 80 rows are shown.
The save/preview buttons are visible and usable.

Arctic Template:
Edit big table.
57 rows are shown. The table lays over the bottom of the page. No buttons visible.
Double clicking on the table shows a few more rows until all 80 rows are shown.
The save/preview buttons are under the table and out of reach. 

Hope this helps.

**Comment by splitbrain** [comment] 2015-09-01 13:36
@micgro42 can you have a look at this please?

**Comment by micgro42** [comment] 2015-09-01 15:12
I can reproduce the issue with the three templates.

I would consider the starterbootstrap template to be conflicting  / incompatible with edittable, since it seems to also include a sort-column functionality which breaks the movement of columns.

The same functionality that enables the plugin to work well with the dokuwiki template breaks it with the other templates. I will look into adapting the plugin to the other templates or vice versa.

**Comment by micgro42** [comment] 2015-09-01 16:00
I pushed a css fix to editable master which should have fixed the issues here. Please test it and tell me if it improved the situation.

**Comment by havarha** [comment] 2015-09-01 16:22
Doesn't seem to help in my case...

**Comment by stevenj** [comment] 2015-09-01 16:56
But it does in mine.  Bootstrap 3 template now has the Save Buttons/etc pushed below my large table.

**Comment by havarha** [comment] 2015-09-01 16:58
I would just like to point out that the buttons are there until I try to change something in the table. After adding a row, editing a value etc the buttons jumps up and disappears behind the table.

**Comment by havarha** [comment] 2015-09-01 17:06
Hmmm... It could have been some caching or something in my browser, but it seems to work better now. Now they are almost completely hidden until I change something, and after changing something I can see a bit more than half the height of them.

**Comment by splitbrain** [comment] 2015-09-01 17:08
@havarha could you post a screenshot?

**Comment by havarha** [comment] 2015-09-01 17:11
Before doing anything:
![image](https://cloud.githubusercontent.com/assets/9715915/9610963/24f7617c-50dd-11e5-93d7-c256e52bf0ae.png)
After adding a row:
![image](https://cloud.githubusercontent.com/assets/9715915/9610966/2d527960-50dd-11e5-9d65-ec817f3d5279.png)

**Comment by winnuker** [comment] 2015-09-01 17:34
Thank you very much.

edittable now works fine with DokuWiki template and Arctic template (and big tables).

**Comment by konus1** [comment] 2015-09-02 11:35
> Firefox (40.0.2) and Chrome (45) with DokuWiki Template:
Edit big table
24 Rows are shown.
Click on the table -> 37 rows are shown.
Click on the table -> 52 rows are shown.
Click on the table -> 70 rows are shown.
Click on the table -> all 80 rows are shown.

Is this the normal behavior now? I found it very annoying, because you always have to multiclick to expand the table, before you can save or cancel.

**Comment by splitbrain** [comment] 2015-09-02 14:52
@konus1 no. this should be fixed in the dokuwiki template now. What browser and template do you use?

**Comment by konus1** [comment] 2015-09-02 15:40
I use Firefox 40.0.3.  Dokuwiki 2015-08-10a "Detritus" with the default Dokuwiki template. I used edittable Version 2015-08-27 and manually now merged commit "Fix table in arctic and bootstrap3 template" into my installation.
The behavior did not change.

Where can I find a fixed dokuwiki template? I was searching at https://github.com/splitbrain/dokuwiki but the last change was 5 days ago a translation update.

**Comment by micgro42** [comment] 2015-09-03 12:48
@konus1  The dokuwiki template did not change, but the css in edittable which caused this behaviour changed with the latest commit. However since css is cached both by the browser and by the server you may have to actively clear both caches to see the change.

To clear the dokuwiki cache either touch `conf/local.php` or simply save your current configuration in the admin menu again, which will also invalidate the dokuwiki cache.
You can clear you browser cache by reloading with `Shift+F5` or `Ctrl+Shift+R` or something similar depending on your browser.

**Comment by konus1** [comment] 2015-09-04 12:58
After installing edittable version 2015-09-01 the problem not showing all rows at once is solved for me.Thank you!

**Comment by micgro42** [comment] 2017-08-10 16:07
This seems to be resolved.

**Closed by micgro42** 2017-08-10 16:07 UTC
