### ISSUE TITLE
Version ""2015-06-17" conflicts with indexmenu?

### ISSUE THREAD

**Issue by JMStranz** [cosmocode/edittable#82] opened 2015-08-21 06:11 UTC
I'm running DokuWiki (Release 2014-09-29d "Hrun") with template "monobook" (version 2014-02-09).
For navigation I'm using the plugin "indexmenu" (https://www.dokuwiki.org/plugin:indexmenu) in order to have a nice index in the "navigation" field.
Each "index page" has the following entry:

`~~NOTOC~~`
====== Title ======
{{indexmenu>.#1|js nsort msort navbar notoc noscroll}}

After updating the plugin "edittable" with the newest version "2015-06-17" the appearance of the indexmenu changes and only the almost top entry is shown.
I've had to reinstall the previous version of the plugin ("2015-05-15").

Is there any known issue or conflict?

**Comment by micgro42** [comment] 2015-08-21 09:17
The edittable plugin has recently received a major update of the underlying 3rd party library and this may have introduced some conflicts with other plugins. There has been a report of a conflict with the tagging plugin (see cosmocode/tagging#22) as well.

Those issues should hopefully be resolved within the next week.

**Comment by splitbrain** [comment] 2015-08-21 11:34
@JMStranz can you provide possible error messages from the JavaScript console please?

**Comment by JMStranz** [comment] 2015-08-21 11:58
I'm not experienced neither with java nor with web development.
Please giive a short description in order to obtain "error messages from the JavaScript console".
I'm usally working with Firefox if this matters.

**Comment by splitbrain** [comment] 2015-08-21 12:34
@JMStranz see https://www.dokuwiki.org/bugs#javascript_console_log

**Comment by Mathilu** [comment] 2015-08-24 15:21
I also have problems with edittable plugin since an update to 2015-08-18 today. Dokuwiki is also extremely slow (running on an Raspi 1 with nginx). With edittable deactivated, everything is okay. 
Firefox shows me this JS error:
17:19:42.361 ReferenceError: DOKU_BASE is not defined1 script-cmpr.js:1:5893

**Comment by Mathilu** [comment] 2015-08-27 06:51
with the latest indexmenu update (2015-08-26) the behavior didn't change. Dokuwiki is slow, indexmenu is broken and i get this JS errors in Firefox:
ReferenceError: dTree is not defined start:121:5
ReferenceError: DOKU_BASE is not defined script-cmpr.js:1:5893

**Comment by splitbrain** [comment] 2015-08-27 06:55
@Mathilu your symptoms seem very different from the problems we fixed with the indexmenu incompatibility. Could you open a aeparate issue please?

**Closed** 2015-09-04 15:16 UTC
Labels: bug

**Comment by JMStranz** [comment] 2015-09-05 13:24
I've seeen, that this issue have been closed.

I've updated the plugin "indexmenu" to version "2015-08-26" and then the plugin "edittable" to version "2015-09-01".
Unfortunately the problem I've described is still existent.

**Comment by micgro42** [comment] 2015-09-14 07:25
It turns out to be caused by a bug in the js compression in Hrun. An update of DokuWiki to Detritus should fix it. See also issue #90

**Comment by micgro42** [comment] 2015-09-14 07:43
Also fixed in the newest edittable version.
